export const homeObjOne = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel1: 'Comprar un auto',
    buttonLabel2: 'Vender un auto',
    description: ' Te ofrecemos la mejor experiencia de compra y venta de autos en Caracas.',
    headline: 'Los mejores precios en autos.',
    lightText: true,
    topLine: 'Concesionario de vehículos',
    img: require('../../images/tundra.png'),
    alt: 'Image',
    start: '',
    buttonDisplay: true,
};

export const homeObjTwo = {
    lightBg: true,
    primary: true,
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel1: 'Comprar un auto',
    buttonLabel2: 'Vender un auto',
    description: 'Programamos la inspección de manera rápida y segura en nuestra sede',
    headline: '¿Quieres vender tu auto?',
    lightText: false,
    topLine: '',
    img: require('../../images/iphone13.png'),
    alt: 'Image',
    start: '',
    buttonDisplay: false,
};

