export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_LATEST = 'FETCH_LATEST';
export const FETCH_RECOMMENDATION = 'FETCH_RECOMMENDATION';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';